### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LucSieben** [node-red/node-red.github.io#210]
Hi,
Since yesterday i got the following error,

Welcome to Node-RED
===================

18 Mar 09:42:15 - [info] Node-RED version: v1.2.9
18 Mar 09:42:15 - [info] Node.js  version: v14.16.0
18 Mar 09:42:15 - [info] Windows_NT 10.0.19042 x64 LE
18 Mar 09:42:16 - [info] Loading palette nodes
18 Mar 09:42:18 - [info] UI started at /ui
18 Mar 09:42:19 - [info] Settings file  : C:\Users\LucSieben\.node-red\settings.js
18 Mar 09:42:19 - [info] Context store  : 'default' [module=memory]
18 Mar 09:42:19 - [info] User directory : \Users\LucSieben\.node-red
18 Mar 09:42:19 - [warn] Projects disabled : editorTheme.projects.enabled=false
18 Mar 09:42:19 - [info] Flows file     : \Users\LucSieben\.node-red\flows_ATNED39.json
18 Mar 09:42:19 - [info] Server now running at http://127.0.0.1:1880/
18 Mar 09:42:19 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

18 Mar 09:42:19 - [info] Waiting for missing types to be registered:
18 Mar 09:42:19 - [info]  - nefit-easy-config

And when I tried to start something in Node Red, their is a popup that says "Error: node not deployed" 
Does anyone know how to fix this?

thanks you already,

Luc

**Comment by hardillb** [comment]
This issue tracker is for problems with the Node-RED website, not problems with Node-RED.

The problem is you have a node in your flow that is not installed on your system, specifically `nefit-easy-config` which at a guess will be either of these nodes

 - [node-red-contrib-netfit-easy](https://flows.nodered.org/node/node-red-contrib-nefit-easy)
 - [node-red-contrib-netfit-easy2](https://flows.nodered.org/node/node-red-contrib-nefit-easy2)
 
You need to install one of them, but given they both use the same node names it not possible to say which.

**Comment by LucSieben** [comment]
Thank you for your reply, I solved it already forgot to close the comment i am sorry.
I  had some node running in the background while I deleted them, stupid faulth from me.

thanks.
