### ISSUE TITLE
Users should not run npm on sudo

### ISSUE THREAD

**Issue by machad0** [node-red/node-red.github.io#53]
Hello,

I was browsing a few documentations guidelines and most of the npm commands instructions are running on sudo. This is not a recommended practice, since is unsafe, can lead to scopes problems and well, IMHO, doesn't make sense.

here a few articles telling about and how to fix it as well:
https://pawelgrzybek.com/fix-priviliges-and-never-again-use-sudo-with-npm/
https://docs.npmjs.com/getting-started/fixing-npm-permissions
https://coderwall.com/p/t2mc9g/don-t-sudo-npm
https://johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/

I can fix it if you guys agree

**Comment by dceejay** [comment]
Hi
thanks for this. Usually we prefer things to be discussed on the mailing list (google group) or slack channel first so the widest audience can participate in the debate.

The reason the commands we have are run as sudo is so that they are installed globally and the command line commands get installed in the simplest possible manner for users. The main instance is the install of the core of Node-RED so that the node-red command becomes available. Most of the other instances in the docs are to do with upgrading npm itself which if already installed globally (eg using the node.js install script or any of the package mangers) will need upgrading globally. 

We always advise users not to install nodes using sudo - and to just install them locally in ~/.node-red. We also advise users not to run Node-RED as root/sudo. Of course users are free to install without sudo and we do have a section on running from a local install, (which of course could be improved)

All the doc you link to show torturous methods for avoiding this... That few beginners will understand or get correct - especially cross platform.

**Comment by machad0** [comment]
Hey,

I see, I'll opened a thread there now and I'm closing the issue by now.

**Comment by machad0** [comment]
discussion link: https://groups.google.com/forum/#!topic/node-red/UPQddn4OMrM

I'm closing the issue here by now, thank you!

**Comment by dceejay** [comment]
Thanks - I think it will be a lively one
